#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 10, 2020 09:28:39 PM +07  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #ffffff
set vTcl(pr,menuanalogcolor) #ffffff
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x720+734+134
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Setting"
    vTcl:DefineAlias "$top" "SettingWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu44 \
        -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu44" "TButtonCancel" vTcl:WidgetProc "SettingWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu45 \
        -takefocus {} -text Save 
    vTcl:DefineAlias "$top.tBu45" "TButtonSave" vTcl:WidgetProc "SettingWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu46 \
        -takefocus {} -text About 
    vTcl:DefineAlias "$top.tBu46" "TButtonAbout" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa47 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text Tlabel -image image20 
    vTcl:DefineAlias "$top.tLa47" "TLabelLogo" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa48 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text Tlabel -image image21 
    vTcl:DefineAlias "$top.tLa48" "TLabelLogotext" vTcl:WidgetProc "SettingWindow" 1
    ttk::entry $top.tEn49 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn49" "TEntryAlamat" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa50 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {ALAMAT :} 
    vTcl:DefineAlias "$top.tLa50" "TLabelAlamat" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {*Saat ini :} 
    vTcl:DefineAlias "$top.tLa51" "TLabelSaatIni1" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {{}} -textvariable AlamatSaatIniVar 
    vTcl:DefineAlias "$top.tLa52" "TLabelAlamatSaatIni" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {WEBSITE KAM ITB :} 
    vTcl:DefineAlias "$top.tLa53" "TLabelWebsite" vTcl:WidgetProc "SettingWindow" 1
    ttk::entry $top.tEn54 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn54" "TEntryWebsite" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa55 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {*Saat ini :} 
    vTcl:DefineAlias "$top.tLa55" "TLabelSaatIni2" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa56 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -textvariable WebsiteSaatIniVar 
    vTcl:DefineAlias "$top.tLa56" "TLabelWebsiteSaatIni" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa57 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {KEPALA BIRO LAUNDRY :} 
    vTcl:DefineAlias "$top.tLa57" "TLabelKabir" vTcl:WidgetProc "SettingWindow" 1
    ttk::entry $top.tEn58 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn58" "TEntryKabir" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa59 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {*Saat ini :} 
    vTcl:DefineAlias "$top.tLa59" "TLabelSaatIni3" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa60 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -textvariable KabirSaatIniVar 
    vTcl:DefineAlias "$top.tLa60" "TLabelKabirSaatIni" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa61 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {LOGO LAUNDRY KAM ITB :} 
    vTcl:DefineAlias "$top.tLa61" "TLabelLogoLaundry" vTcl:WidgetProc "SettingWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu62 \
        -takefocus {} -text {Select image} 
    vTcl:DefineAlias "$top.tBu62" "TButtonLogoLaundry" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa63 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {*Saat ini :} 
    vTcl:DefineAlias "$top.tLa63" "TLabelSaatIni4" vTcl:WidgetProc "SettingWindow" 1
    ttk::label $top.tLa64 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -textvariable LogoSaatIniVar 
    vTcl:DefineAlias "$top.tLa64" "TLabelLogoSaatIni" vTcl:WidgetProc "SettingWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu44 \
        -in $top -x 0 -relx 0.767 -y 0 -rely 0.917 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu45 \
        -in $top -x 0 -relx 0.583 -y 0 -rely 0.917 -width 98 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu46 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.917 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.028 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.089 -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 0 -relx 0.433 -y 0 -rely 0.042 -width 0 -relwidth 0.258 \
        -height 0 -relheight 0.075 -anchor nw -bordermode ignore 
    place $top.tEn49 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.208 -width 436 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.167 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.25 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.25 -width 0 -relwidth 0.608 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.319 -width 0 -relwidth 0.22 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.tEn54 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.361 -width 0 -relwidth 0.727 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.403 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.tLa56 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.403 -width 0 -relwidth 0.608 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tLa57 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.472 -width 0 -relwidth 0.287 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.tEn58 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.514 -width 0 -relwidth 0.727 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.tLa59 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.556 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.tLa60 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.556 -width 0 -relwidth 0.608 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tLa61 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.625 -width 0 -relwidth 0.303 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.tBu62 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.667 -width 438 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa63 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.708 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.tLa64 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.708 -width 0 -relwidth 0.608 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

