#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 10, 2020 09:28:39 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import data.gui.setting.Setting_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    data.gui.setting.Setting_support.set_Tk_var()
    top = SettingWindow (root)
    data.gui.setting.Setting_support.init(root, top)
    root.mainloop()

w = None
def create_SettingWindow(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_SettingWindow(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    data.gui.setting.Setting_support.set_Tk_var()
    top = SettingWindow (w)
    data.gui.setting.Setting_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_SettingWindow():
    global w
    w.destroy()
    w = None

class SettingWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 9"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font=font9)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x720+5+5")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(0, 0)
        top.title("Setting")
        top.configure(background="#ffffff")

        self.TButtonBack = ttk.Button(top)
        self.TButtonBack.place(relx=0.767, rely=0.917, height=30, width=98)
        self.TButtonBack.configure(takefocus="")
        self.TButtonBack.configure(text='''Back''')
        self.TButtonBack.configure(command=data.gui.setting.Setting_support.tButtonBackCommand)

        self.TButtonSave = ttk.Button(top)
        self.TButtonSave.place(relx=0.583, rely=0.917, height=30, width=98)
        self.TButtonSave.configure(takefocus="")
        self.TButtonSave.configure(text='''Save''')
        self.TButtonSave.configure(command=data.gui.setting.Setting_support.tButtonSaveCommand)

        self.TButtonAbout = ttk.Button(top)
        self.TButtonAbout.place(relx=0.067, rely=0.917, height=30, width=98)
        self.TButtonAbout.configure(takefocus="")
        self.TButtonAbout.configure(text='''About''')
        self.TButtonAbout.configure(command=data.gui.setting.Setting_support.tButtonAboutCommand)

        self.TLabelLogo = ttk.Label(top)
        self.TLabelLogo.place(relx=0.317, rely=0.028, height=64, width=64)
        self.TLabelLogo.configure(background="#ffffff")
        self.TLabelLogo.configure(foreground="#000000")
        self.TLabelLogo.configure(font=font9)
        self.TLabelLogo.configure(relief="flat")
        self.TLabelLogo.configure(anchor='w')
        self.TLabelLogo.configure(justify='left')
        self.TLabelLogo.configure(text='''Tlabel''')
        photo_location = os.path.join(prog_location,"data/gui/setting/img/setting.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.TLabelLogo.configure(image=_img0)

        self.TLabelLogotext = ttk.Label(top)
        self.TLabelLogotext.place(relx=0.433, rely=0.042, height=54, width=155)
        self.TLabelLogotext.configure(background="#ffffff")
        self.TLabelLogotext.configure(foreground="#000000")
        self.TLabelLogotext.configure(font=font9)
        self.TLabelLogotext.configure(relief="flat")
        self.TLabelLogotext.configure(anchor='w')
        self.TLabelLogotext.configure(justify='left')
        self.TLabelLogotext.configure(text='''Tlabel''')
        photo_location = os.path.join(prog_location,"data/gui/setting/img/logotext.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.TLabelLogotext.configure(image=_img1)

        self.TLabelAlamat = ttk.Label(top)
        self.TLabelAlamat.place(relx=0.133, rely=0.166, height=24, width=72)
        self.TLabelAlamat.configure(background="#ffffff")
        self.TLabelAlamat.configure(foreground="#000000")
        self.TLabelAlamat.configure(font=font9)
        self.TLabelAlamat.configure(relief="flat")
        self.TLabelAlamat.configure(anchor='w')
        self.TLabelAlamat.configure(justify='left')
        self.TLabelAlamat.configure(text='''ALAMAT :''')
        
        self.TEntryAlamat = ttk.Entry(top)
        self.TEntryAlamat.place(relx=0.133, rely=0.208, relheight=0.036
                , relwidth=0.727)
        self.TEntryAlamat.configure(takefocus="")
        self.TEntryAlamat.configure(cursor="ibeam")
        self.TEntryAlamat.configure(textvariable=data.gui.setting.Setting_support.EntryAlamatVar)

        self.TLabelSaatIni1 = ttk.Label(top)
        self.TLabelSaatIni1.place(relx=0.133, rely=0.25, height=24, width=68)
        self.TLabelSaatIni1.configure(background="#ffffff")
        self.TLabelSaatIni1.configure(foreground="#000000")
        self.TLabelSaatIni1.configure(font=font9)
        self.TLabelSaatIni1.configure(relief="flat")
        self.TLabelSaatIni1.configure(anchor='w')
        self.TLabelSaatIni1.configure(justify='left')
        self.TLabelSaatIni1.configure(text='''*Saat ini :''')

        self.TLabelAlamatSaatIni = ttk.Label(top)
        self.TLabelAlamatSaatIni.place(relx=0.22, rely=0.25, height=24
                , width=385)
        self.TLabelAlamatSaatIni.configure(background="#ffffff")
        self.TLabelAlamatSaatIni.configure(foreground="#000000")
        self.TLabelAlamatSaatIni.configure(font=font9)
        self.TLabelAlamatSaatIni.configure(relief="flat")
        self.TLabelAlamatSaatIni.configure(anchor='w')
        self.TLabelAlamatSaatIni.configure(justify='left')
        self.TLabelAlamatSaatIni.configure(textvariable=data.gui.setting.Setting_support.AlamatSaatIniVar)

        self.TLabelWebsite = ttk.Label(top)
        self.TLabelWebsite.place(relx=0.133, rely=0.289, height=23, width=132)
        self.TLabelWebsite.configure(background="#ffffff")
        self.TLabelWebsite.configure(foreground="#000000")
        self.TLabelWebsite.configure(font="-family {Segoe UI} -size 9")
        self.TLabelWebsite.configure(relief="flat")
        self.TLabelWebsite.configure(anchor='w')
        self.TLabelWebsite.configure(justify='left')
        self.TLabelWebsite.configure(text='''WEBSITE KAM ITB :''')
        
        self.TEntryWebsite = ttk.Entry(top)
        self.TEntryWebsite.place(relx=0.133, rely=0.331, relheight=0.036
                , relwidth=0.727)
        self.TEntryWebsite.configure(takefocus="")
        self.TEntryWebsite.configure(cursor="ibeam")
        self.TEntryWebsite.configure(textvariable=data.gui.setting.Setting_support.EntryWebsiteVar)

        self.TLabelSaatIni2 = ttk.Label(top)
        self.TLabelSaatIni2.place(relx=0.133, rely=0.373, height=23, width=68)
        self.TLabelSaatIni2.configure(background="#ffffff")
        self.TLabelSaatIni2.configure(foreground="#000000")
        self.TLabelSaatIni2.configure(font="-family {Segoe UI} -size 9")
        self.TLabelSaatIni2.configure(relief="flat")
        self.TLabelSaatIni2.configure(anchor='w')
        self.TLabelSaatIni2.configure(justify='left')
        self.TLabelSaatIni2.configure(text='''*Saat ini :''')

        self.TLabelWebsiteSaatIni = ttk.Label(top)
        self.TLabelWebsiteSaatIni.place(relx=0.22, rely=0.373, height=24
                , width=385)
        self.TLabelWebsiteSaatIni.configure(background="#ffffff")
        self.TLabelWebsiteSaatIni.configure(foreground="#000000")
        self.TLabelWebsiteSaatIni.configure(font="-family {Segoe UI} -size 9")
        self.TLabelWebsiteSaatIni.configure(relief="flat")
        self.TLabelWebsiteSaatIni.configure(anchor='w')
        self.TLabelWebsiteSaatIni.configure(justify='left')
        self.TLabelWebsiteSaatIni.configure(textvariable=data.gui.setting.Setting_support.WebsiteSaatIniVar)

        self.TLabelKabir = ttk.Label(top)
        self.TLabelKabir.place(relx=0.133, rely=0.412, height=23, width=172)
        self.TLabelKabir.configure(background="#ffffff")
        self.TLabelKabir.configure(foreground="#000000")
        self.TLabelKabir.configure(font="-family {Segoe UI} -size 9")
        self.TLabelKabir.configure(relief="flat")
        self.TLabelKabir.configure(anchor='w')
        self.TLabelKabir.configure(justify='left')
        self.TLabelKabir.configure(text='''KEPALA BIRO LAUNDRY :''')
        
        self.TEntryKabir = ttk.Entry(top)
        self.TEntryKabir.place(relx=0.133, rely=0.454, relheight=0.036
                , relwidth=0.727)
        self.TEntryKabir.configure(takefocus="")
        self.TEntryKabir.configure(cursor="ibeam")
        self.TEntryKabir.configure(textvariable=data.gui.setting.Setting_support.EntryKabirVar)

        self.TLabelSaatIni3 = ttk.Label(top)
        self.TLabelSaatIni3.place(relx=0.133, rely=0.496, height=23, width=68)
        self.TLabelSaatIni3.configure(background="#ffffff")
        self.TLabelSaatIni3.configure(foreground="#000000")
        self.TLabelSaatIni3.configure(font="-family {Segoe UI} -size 9")
        self.TLabelSaatIni3.configure(relief="flat")
        self.TLabelSaatIni3.configure(anchor='w')
        self.TLabelSaatIni3.configure(justify='left')
        self.TLabelSaatIni3.configure(text='''*Saat ini :''')

        self.TLabelKabirSaatIni = ttk.Label(top)
        self.TLabelKabirSaatIni.place(relx=0.22, rely=0.496, height=24
                , width=385)
        self.TLabelKabirSaatIni.configure(background="#ffffff")
        self.TLabelKabirSaatIni.configure(foreground="#000000")
        self.TLabelKabirSaatIni.configure(font="-family {Segoe UI} -size 9")
        self.TLabelKabirSaatIni.configure(relief="flat")
        self.TLabelKabirSaatIni.configure(anchor='w')
        self.TLabelKabirSaatIni.configure(justify='left')
        self.TLabelKabirSaatIni.configure(textvariable=data.gui.setting.Setting_support.KabirSaatIniVar)

        self.TLabelGaji = ttk.Label(top)
        self.TLabelGaji.place(relx=0.133, rely=0.535, height=23
                , width=182)
        self.TLabelGaji.configure(background="#ffffff")
        self.TLabelGaji.configure(foreground="#000000")
        self.TLabelGaji.configure(font="-family {Segoe UI} -size 9")
        self.TLabelGaji.configure(relief="flat")
        self.TLabelGaji.configure(anchor='w')
        self.TLabelGaji.configure(justify='left')
        self.TLabelGaji.configure(text='''GAJI PERJAM :''')
        
        self.TEntryGaji = ttk.Entry(top)
        self.TEntryGaji.place(relx=0.133, rely=0.577, relheight=0.036
                , relwidth=0.727)
        self.TEntryGaji.configure(takefocus="")
        self.TEntryGaji.configure(cursor="ibeam")
        self.TEntryGaji.configure(textvariable=data.gui.setting.Setting_support.EntryGajiVar)

        self.TLabelSaatIni5 = ttk.Label(top)
        self.TLabelSaatIni5.place(relx=0.133, rely=0.618, height=23, width=68)
        self.TLabelSaatIni5.configure(background="#ffffff")
        self.TLabelSaatIni5.configure(foreground="#000000")
        self.TLabelSaatIni5.configure(font="-family {Segoe UI} -size 9")
        self.TLabelSaatIni5.configure(relief="flat")
        self.TLabelSaatIni5.configure(anchor='w')
        self.TLabelSaatIni5.configure(justify='left')
        self.TLabelSaatIni5.configure(text='''*Saat ini :''')

        self.TLabelGajiSaatIni = ttk.Label(top)
        self.TLabelGajiSaatIni.place(relx=0.22, rely=0.618, height=24, width=385)
        self.TLabelGajiSaatIni.configure(background="#ffffff")
        self.TLabelGajiSaatIni.configure(foreground="#000000")
        self.TLabelGajiSaatIni.configure(font="-family {Segoe UI} -size 9")
        self.TLabelGajiSaatIni.configure(relief="flat")
        self.TLabelGajiSaatIni.configure(anchor='w')
        self.TLabelGajiSaatIni.configure(justify='left')
        self.TLabelGajiSaatIni.configure(textvariable=data.gui.setting.Setting_support.GajiSaatIniVar)

        self.TLabelLogoLaundry = ttk.Label(top)
        self.TLabelLogoLaundry.place(relx=0.133, rely=0.657, height=23
                , width=182)
        self.TLabelLogoLaundry.configure(background="#ffffff")
        self.TLabelLogoLaundry.configure(foreground="#000000")
        self.TLabelLogoLaundry.configure(font="-family {Segoe UI} -size 9")
        self.TLabelLogoLaundry.configure(relief="flat")
        self.TLabelLogoLaundry.configure(anchor='w')
        self.TLabelLogoLaundry.configure(justify='left')
        self.TLabelLogoLaundry.configure(text='''LOGO LAUNDRY KAM ITB :''')

        self.TButtonLogoLaundry = ttk.Button(top)
        self.TButtonLogoLaundry.place(relx=0.133, rely=0.699, height=30
                , width=438)
        self.TButtonLogoLaundry.configure(takefocus="")
        self.TButtonLogoLaundry.configure(text='''Select image''')
        self.TButtonLogoLaundry.configure(command=data.gui.setting.Setting_support.tButtonLogoLaundryCommand)

        self.TLabelSaatIni4 = ttk.Label(top)
        self.TLabelSaatIni4.place(relx=0.133, rely=0.740, height=23, width=68)
        self.TLabelSaatIni4.configure(background="#ffffff")
        self.TLabelSaatIni4.configure(foreground="#000000")
        self.TLabelSaatIni4.configure(font="-family {Segoe UI} -size 9")
        self.TLabelSaatIni4.configure(relief="flat")
        self.TLabelSaatIni4.configure(anchor='w')
        self.TLabelSaatIni4.configure(justify='left')
        self.TLabelSaatIni4.configure(text='''*Saat ini :''')

        self.TLabelLogoSaatIni = ttk.Label(top)
        self.TLabelLogoSaatIni.place(relx=0.22, rely=0.740, height=24, width=385)
        self.TLabelLogoSaatIni.configure(background="#ffffff")
        self.TLabelLogoSaatIni.configure(foreground="#000000")
        self.TLabelLogoSaatIni.configure(font="-family {Segoe UI} -size 9")
        self.TLabelLogoSaatIni.configure(relief="flat")
        self.TLabelLogoSaatIni.configure(anchor='w')
        self.TLabelLogoSaatIni.configure(justify='left')
        self.TLabelLogoSaatIni.configure(textvariable=data.gui.setting.Setting_support.LogoSaatIniVar)

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.135, rely=0.810, relheight=0.063
                , relwidth=0.730)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief="groove")

        self.TLabelStatus = ttk.Label(self.TFrame1)
        self.TLabelStatus.place(relx=0.022, rely=0.222, height=24, width=410)
        self.TLabelStatus.configure(background="#ffffff")
        self.TLabelStatus.configure(foreground="#000000")
        self.TLabelStatus.configure(font="-family {Segoe UI} -size 9")
        self.TLabelStatus.configure(relief="flat")
        self.TLabelStatus.configure(anchor='c')
        self.TLabelStatus.configure(justify='left')
        self.TLabelStatus.configure(textvariable=data.gui.setting.Setting_support.TlabelStatusVar)
