#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 13, 2020 11:23:37 PM +07  platform: Windows NT

import sys
import webbrowser

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import data.gui.setting.Setting

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def TButtonBackCommand():
    # utup halaman about
    destroy_window()
    # Buka halaman setting
    data.gui.setting.Setting.vp_start_gui()

def TButtonContactCommand():
    new = 1
    url = "https://muhanggarisfanani.typeform.com/to/xeUK8L"
    webbrowser.open(url,1)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
