#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 10, 2020 02:00:14 PM +07  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #ffffff
set vTcl(pr,menuanalogcolor) #ffffff
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1366x768+5+5
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Welcome, Tropical Laundry Sangkuring"
    vTcl:DefineAlias "$top" "BeginWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu44 \
        -takefocus {} -text GENERATE 
    vTcl:DefineAlias "$top.tBu44" "ButtonGenerate" vTcl:WidgetProc "BeginWindow" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr46 \
        -borderwidth 2 -relief groove -width 735 -height 555 
    vTcl:DefineAlias "$top.tFr46" "TFrameLogo" vTcl:WidgetProc "BeginWindow" 1
    set site_3_0 $top.tFr46
    ttk::label $site_3_0.tLa47 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -image image20 
    vTcl:DefineAlias "$site_3_0.tLa47" "TLabelLogoImage" vTcl:WidgetProc "BeginWindow" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_3_0.tFr48 \
        -borderwidth 2 -relief groove -width 525 -height 95 
    vTcl:DefineAlias "$site_3_0.tFr48" "TFrameTitle" vTcl:WidgetProc "BeginWindow" 1
    set site_4_0 $site_3_0.tFr48
    ttk::label $site_4_0.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI Black} -size 18 -weight bold} -relief flat \
        -anchor w -justify center -text {AUTO SALARY SLIP GENERATOR} 
    vTcl:DefineAlias "$site_4_0.tLa49" "TLabelTitle" vTcl:WidgetProc "BeginWindow" 1
    place $site_4_0.tLa49 \
        -in $site_4_0 -x 0 -relx 0.038 -y 0 -rely 0.118 -width 0 \
        -relwidth 0.924 -height 0 -relheight 0.753 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 0 -relx 0.327 -y 0 -rely 0.378 -width 0 \
        -relwidth 0.294 -height 0 -relheight 0.476 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tFr48 \
        -in $site_3_0 -x 0 -relx 0.15 -y 0 -rely 0.144 -width 0 \
        -relwidth 0.714 -height 0 -relheight 0.171 -anchor nw \
        -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu51 \
        -takefocus {} -image image21 
    vTcl:DefineAlias "$top.tBu51" "TButtonSettingImage" vTcl:WidgetProc "BeginWindow" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa52 \
        -text {Muhammad Angga Risfanani ~ copyright© 2020 Powered by Python3} \
        -width 735 -height 45 
    vTcl:DefineAlias "$top.tLa52" "TLabelframeCopyright" vTcl:WidgetProc "BeginWindow" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa54 \
        -text Status -width 357 -height 55 
    vTcl:DefineAlias "$top.tLa54" "TLabelframeStatus" vTcl:WidgetProc "BeginWindow" 1
    set site_3_0 $top.tLa54
    ttk::label $site_3_0.tLa55 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -textvariable LabelStatusVar 
    vTcl:DefineAlias "$site_3_0.tLa55" "TLabelStatus" vTcl:WidgetProc "BeginWindow" 1
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 0 -relx 0.028 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.938 -height 0 -relheight 0.491 -anchor nw \
        -bordermode ignore 
    ttk::separator $top.tSe57
    vTcl:DefineAlias "$top.tSe57" "TSeparator1" vTcl:WidgetProc "BeginWindow" 1
    ttk::label $top.tLa61 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -image image24 
    vTcl:DefineAlias "$top.tLa61" "TLabelSettingH" vTcl:WidgetProc "BeginWindow" 1
    ttk::separator $top.tSe64
    vTcl:DefineAlias "$top.tSe64" "TSeparator1_1" vTcl:WidgetProc "BeginWindow" 1
    ttk::label $top.tLa69 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left \
        -text {Kamu harus memasukkan file absensi terlebih dahulu} 
    vTcl:DefineAlias "$top.tLa69" "TLabelLoadInstruction" vTcl:WidgetProc "BeginWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu70 \
        -takefocus {} -text Browse 
    vTcl:DefineAlias "$top.tBu70" "TButtonBrowseFile" vTcl:WidgetProc "BeginWindow" 1
    ttk::label $top.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {{}} -textvariable LabelPathFileVar 
    vTcl:DefineAlias "$top.tLa71" "TLabelPathFile" vTcl:WidgetProc "BeginWindow" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa79 \
        -text Panduan -width 351 -height 245 
    vTcl:DefineAlias "$top.tLa79" "TLabelframePanduan" vTcl:WidgetProc "BeginWindow" 1
    set site_3_0 $top.tLa79
    ttk::label $site_3_0.tLa81 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left \
        -text {1. Pastikan file yang akan dimasukkan dalam
    format excel (xlx/xlsx) Monthly Report
    serta sudah mengatur konfigurasi setting,
2. Tekan tombol "Browse" di atas untuk mencari
    file,
3. Lalu pilih karyawan yang akan di-generate slip
    gajinya (Peringatan! Jangan men-generate slip
    gaji untuk selain karyawan),
4. Tekan tombol "Generate" di bawah untuk
    menyimpan softfile slip gaji.} 
    vTcl:DefineAlias "$site_3_0.tLa81" "TLabelPanduanChild" vTcl:WidgetProc "BeginWindow" 1
    place $site_3_0.tLa81 \
        -in $site_3_0 -x 0 -relx 0.028 -y 0 -rely 0.082 -width 0 \
        -relwidth 0.952 -height 0 -relheight 0.865 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu44 \
        -in $top -x 0 -relx 0.666 -y 0 -rely 0.742 -width 355 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tFr46 \
        -in $top -x 0 -relx 0.081 -y 0 -rely 0.13 -width 0 -relwidth 0.538 \
        -height 0 -relheight 0.723 -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 0 -relx 0.867 -y 0 -rely 0.13 -width 74 -relwidth 0 \
        -height 74 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 0 -relx 0.081 -y 0 -rely 0.872 -width 0 -relwidth 0.538 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tLa54 \
        -in $top -x 0 -relx 0.666 -y 0 -rely 0.859 -width 0 -relwidth 0.26 \
        -height 0 -relheight 0.072 -anchor nw -bordermode ignore 
    place $top.tSe57 \
        -in $top -x 0 -relx 0.659 -y 0 -rely 0.833 -width 0 -relwidth 0.272 \
        -height 0 -relheight 0.003 -anchor nw -bordermode inside 
    place $top.tLa61 \
        -in $top -x 0 -relx 0.67 -y 0 -rely 0.138 -width 0 -relwidth 0.194 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.tSe64 \
        -in $top -x 0 -relx 0.659 -y 0 -rely 0.253 -width 0 -relwidth 0.272 \
        -height 0 -relheight 0.003 -anchor nw -bordermode ignore 
    place $top.tLa69 \
        -in $top -x 0 -relx 0.666 -y 0 -rely 0.286 -width 0 -relwidth 0.26 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.tBu70 \
        -in $top -x 0 -relx 0.666 -y 0 -rely 0.339 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa71 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.342 -width 0 -relwidth 0.179 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.tLa79 \
        -in $top -x 0 -relx 0.666 -y 0 -rely 0.397 -width 0 -relwidth 0.257 \
        -height 0 -relheight 0.319 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

