#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 14, 2020 01:23:14 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from PIL import Image, ImageTk

import data.gui.browse.Browse_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root, top, KasbonWindowapp
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    data.gui.browse.Browse_support.set_Tk_var()
    top = FileWindow (root)
    data.gui.browse.Browse_support.init(root, top)
    root.mainloop()

w = None
def create_FileWindow(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_FileWindow(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    data.gui.browse.Browse_support.set_Tk_var()
    top = FileWindow (w)
    data.gui.browse.Browse_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_FileWindow():
    global w
    w.destroy()
    w = None

class FileWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Times New Roman} -size 12"
        font9 = "-family {Segoe UI} -size 9"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font=font9)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1366x768+5+5")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(0, 0)
        top.title("File Configuration")
        top.configure(background="#ffffff")

        self.TLabelInstruksiBrowseFile = ttk.Label(top)
        self.TLabelInstruksiBrowseFile.place(relx=0.037, rely=0.052, height=24
                , width=613)
        self.TLabelInstruksiBrowseFile.configure(background="#ffffff")
        self.TLabelInstruksiBrowseFile.configure(foreground="#000000")
        self.TLabelInstruksiBrowseFile.configure(font=font9)
        self.TLabelInstruksiBrowseFile.configure(relief="flat")
        self.TLabelInstruksiBrowseFile.configure(anchor='w')
        self.TLabelInstruksiBrowseFile.configure(justify='left')
        self.TLabelInstruksiBrowseFile.configure(text='''Pertama, pilih file absensi terlebih dahulu dengan menekan tombol "Browse File" di bawah.''')

        self.TButtonBrowseFile = ttk.Button(top)
        self.TButtonBrowseFile.place(relx=0.037, rely=0.091, height=30
                , width=118)
        self.TButtonBrowseFile.configure(command=data.gui.browse.Browse_support.TButtonBrowseFileCommand)
        self.TButtonBrowseFile.configure(takefocus="")
        self.TButtonBrowseFile.configure(text='''Browse File''')

        self.TLabelPathFile = ttk.Label(top)
        self.TLabelPathFile.place(relx=0.132, rely=0.096, height=24, width=600)
        self.TLabelPathFile.configure(background="#ffffff")
        self.TLabelPathFile.configure(foreground="#000000")
        self.TLabelPathFile.configure(font=font9)
        self.TLabelPathFile.configure(relief="flat")
        self.TLabelPathFile.configure(anchor='w')
        self.TLabelPathFile.configure(justify='left')
        self.TLabelPathFile.configure(textvariable=data.gui.browse.Browse_support.TLabelPathFileVar)

        self.TLabelContohPathFile = ttk.Label(top)
        self.TLabelContohPathFile.place(relx=0.037, rely=0.13, height=24
                , width=214)
        self.TLabelContohPathFile.configure(background="#ffffff")
        self.TLabelContohPathFile.configure(foreground="#000000")
        self.TLabelContohPathFile.configure(font=font9)
        self.TLabelContohPathFile.configure(relief="flat")
        self.TLabelContohPathFile.configure(anchor='w')
        self.TLabelContohPathFile.configure(justify='left')
        self.TLabelContohPathFile.configure(text='''( Contoh : 01CLOCK-20-02.XLS )''')

        self.TLabelInstruksiEntry = ttk.Label(top)
        self.TLabelInstruksiEntry.place(relx=0.037, rely=0.182, height=24
                , width=623)
        self.TLabelInstruksiEntry.configure(background="#ffffff")
        self.TLabelInstruksiEntry.configure(foreground="#000000")
        self.TLabelInstruksiEntry.configure(font=font9)
        self.TLabelInstruksiEntry.configure(relief="flat")
        self.TLabelInstruksiEntry.configure(anchor='w')
        self.TLabelInstruksiEntry.configure(justify='left')
        self.TLabelInstruksiEntry.configure(text='''Kedua, masukkan periode penggajian dan nominal pemasukan (kotor) pada periode tersebut.''')

        self.TLabelPeriode = ttk.Label(top)
        self.TLabelPeriode.place(relx=0.044, rely=0.221, height=24, width=105)
        self.TLabelPeriode.configure(background="#ffffff")
        self.TLabelPeriode.configure(foreground="#000000")
        self.TLabelPeriode.configure(font=font9)
        self.TLabelPeriode.configure(relief="flat")
        self.TLabelPeriode.configure(anchor='w')
        self.TLabelPeriode.configure(justify='left')
        self.TLabelPeriode.configure(text='''Periode           :''')

        self.TEntryPeriode = ttk.Entry(top)
        self.TEntryPeriode.place(relx=0.124, rely=0.221, relheight=0.034
                , relwidth=0.13)
        self.TEntryPeriode.configure(textvariable=data.gui.browse.Browse_support.TEntryPeriodeVar)
        self.TEntryPeriode.configure(takefocus="")
        self.TEntryPeriode.configure(cursor="ibeam")

        self.TLabelPemasukan = ttk.Label(top)
        self.TLabelPemasukan.place(relx=0.044, rely=0.26, height=23, width=103)
        self.TLabelPemasukan.configure(background="#ffffff")
        self.TLabelPemasukan.configure(foreground="#000000")
        self.TLabelPemasukan.configure(font="-family {Segoe UI} -size 9")
        self.TLabelPemasukan.configure(relief="flat")
        self.TLabelPemasukan.configure(anchor='w')
        self.TLabelPemasukan.configure(justify='left')
        self.TLabelPemasukan.configure(text='''Pemasukan     :''')

        self.TEntryPemasukan = ttk.Entry(top)
        self.TEntryPemasukan.place(relx=0.124, rely=0.26, relheight=0.034
                , relwidth=0.13)
        self.TEntryPemasukan.configure(textvariable=data.gui.browse.Browse_support.TEntryPemasukanVar)
        self.TEntryPemasukan.configure(takefocus="")
        self.TEntryPemasukan.configure(cursor="ibeam")

        self.TLabelContohPeriode = ttk.Label(top)
        self.TLabelContohPeriode.place(relx=0.264, rely=0.221, height=24
                , width=214)
        self.TLabelContohPeriode.configure(background="#ffffff")
        self.TLabelContohPeriode.configure(foreground="#000000")
        self.TLabelContohPeriode.configure(font=font9)
        self.TLabelContohPeriode.configure(relief="flat")
        self.TLabelContohPeriode.configure(anchor='w')
        self.TLabelContohPeriode.configure(justify='left')
        self.TLabelContohPeriode.configure(text='''( Contoh : 01-29 Februari 2020 )''')

        self.TLabelContohPemasukan = ttk.Label(top)
        self.TLabelContohPemasukan.place(relx=0.264, rely=0.26, height=23
                , width=265)
        self.TLabelContohPemasukan.configure(background="#ffffff")
        self.TLabelContohPemasukan.configure(foreground="#000000")
        self.TLabelContohPemasukan.configure(font=font9)
        self.TLabelContohPemasukan.configure(relief="flat")
        self.TLabelContohPemasukan.configure(anchor='w')
        self.TLabelContohPemasukan.configure(justify='left')
        self.TLabelContohPemasukan.configure(text='''( Contoh : 5000000 )''')

        self.TLabelInstruksiPilihKaryawan = ttk.Label(top)
        self.TLabelInstruksiPilihKaryawan.place(relx=0.037, rely=0.3125, height=36
                , width=784)
        self.TLabelInstruksiPilihKaryawan.configure(background="#ffffff")
        self.TLabelInstruksiPilihKaryawan.configure(foreground="#000000")
        self.TLabelInstruksiPilihKaryawan.configure(font=font9)
        self.TLabelInstruksiPilihKaryawan.configure(relief="flat")
        self.TLabelInstruksiPilihKaryawan.configure(anchor='w')
        self.TLabelInstruksiPilihKaryawan.configure(justify='left')
        self.TLabelInstruksiPilihKaryawan.configure(text='''Ketiga, pilih semua karyawan untuk di-generate slip gajinya, serta masukkan kasbon masing-masing karyawan (jika ada).
!!! PERINGATAN PENTING !!! Pilih semua karyawan yg bekerja pada periode di atas, total jam kerja akan dihitung dari semua karyawan yang dipilih.  
''')

        self.TFrameListboxKaryawan = ttk.Frame(top)
        self.TFrameListboxKaryawan.place(relx=0.044, rely=0.365, relheight=0.556
                , relwidth=0.561)
        self.TFrameListboxKaryawan.configure(relief='groove')
        self.TFrameListboxKaryawan.configure(borderwidth="2")
        self.TFrameListboxKaryawan.configure(relief="groove")

        self.ListboxKaryawanTersedia = tk.Listbox(self.TFrameListboxKaryawan)
        self.ListboxKaryawanTersedia.place(relx=0.039, rely=0.117
                , relheight=0.815, relwidth=0.371)
        self.ListboxKaryawanTersedia.configure(activestyle="none")
        self.ListboxKaryawanTersedia.configure(background="white")
        self.ListboxKaryawanTersedia.configure(disabledforeground="#a3a3a3")
        self.ListboxKaryawanTersedia.configure(font=font10)
        self.ListboxKaryawanTersedia.configure(foreground="#000000")
        self.ListboxKaryawanTersedia.configure(relief="groove")

        self.ListboxKaryawanTerpilih = tk.Listbox(self.TFrameListboxKaryawan)
        self.ListboxKaryawanTerpilih.place(relx=0.587, rely=0.117
                , relheight=0.815, relwidth=0.371)
        self.ListboxKaryawanTerpilih.configure(activestyle="none")
        self.ListboxKaryawanTerpilih.configure(background="white")
        self.ListboxKaryawanTerpilih.configure(disabledforeground="#a3a3a3")
        self.ListboxKaryawanTerpilih.configure(font=font10)
        self.ListboxKaryawanTerpilih.configure(foreground="#000000")
        self.ListboxKaryawanTerpilih.configure(relief="ridge")

        self.TButtonAddKaryawan = ttk.Button(self.TFrameListboxKaryawan)
        self.TButtonAddKaryawan.place(relx=0.509, rely=0.468, height=40
                , width=48)
        self.TButtonAddKaryawan.configure(command=data.gui.browse.Browse_support.TButtonAddKaryawanCommand)
        self.TButtonAddKaryawan.configure(takefocus="")
        self.TButtonAddKaryawan.configure(text='''>>''')

        self.TButtonDeleteKaryawan = ttk.Button(self.TFrameListboxKaryawan)
        self.TButtonDeleteKaryawan.place(relx=0.431, rely=0.468, height=40
                , width=48)
        self.TButtonDeleteKaryawan.configure(command=data.gui.browse.Browse_support.TButtonDeleteKaryawan)
        self.TButtonDeleteKaryawan.configure(takefocus="")
        self.TButtonDeleteKaryawan.configure(text='''<<''')

        self.TLabelListKaryawanTersedia = ttk.Label(self.TFrameListboxKaryawan)
        self.TLabelListKaryawanTersedia.place(relx=0.026, rely=0.047, height=24
                , width=190)
        self.TLabelListKaryawanTersedia.configure(background="#ffffff")
        self.TLabelListKaryawanTersedia.configure(foreground="#000000")
        self.TLabelListKaryawanTersedia.configure(font=font9)
        self.TLabelListKaryawanTersedia.configure(relief="flat")
        self.TLabelListKaryawanTersedia.configure(anchor='w')
        self.TLabelListKaryawanTersedia.configure(justify='left')
        self.TLabelListKaryawanTersedia.configure(text='''~ Data yang tersedia :''')

        self.TLabelListKaryawanTerpilih = ttk.Label(self.TFrameListboxKaryawan)
        self.TLabelListKaryawanTerpilih.place(relx=0.574, rely=0.047, height=24
                , width=186)
        self.TLabelListKaryawanTerpilih.configure(background="#ffffff")
        self.TLabelListKaryawanTerpilih.configure(foreground="#000000")
        self.TLabelListKaryawanTerpilih.configure(font="-family {Segoe UI} -size 9")
        self.TLabelListKaryawanTerpilih.configure(relief="flat")
        self.TLabelListKaryawanTerpilih.configure(anchor='w')
        self.TLabelListKaryawanTerpilih.configure(justify='left')
        self.TLabelListKaryawanTerpilih.configure(text='''~ Daftar karyawan terpilih :''')

        self.TButtonGo = ttk.Button(top)
        self.TButtonGo.place(relx=0.769, rely=0.755, height=40, width=138)
        self.TButtonGo.configure(command=data.gui.browse.Browse_support.TButtonGoCommand)
        self.TButtonGo.configure(takefocus="")
        self.TButtonGo.configure(text='''Go''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.637, rely=0.039, relheight=0.897)
        self.TSeparator1.configure(orient="vertical")

        self.TButtonCancel = ttk.Button(top)
        self.TButtonCancel.place(relx=0.769, rely=0.82, height=40, width=138)
        self.TButtonCancel.configure(command=data.gui.browse.Browse_support.TButtonCancelCommand)
        self.TButtonCancel.configure(takefocus="")
        self.TButtonCancel.configure(text='''Cancel''')

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.673, rely=0.664, relwidth=0.294)

        self.TLabelLogo = ttk.Label(top)
        self.TLabelLogo.place(relx=0.673, rely=0.091, height=394, width=405)
        self.TLabelLogo.configure(background="#ffffff")
        self.TLabelLogo.configure(foreground="#000000")
        self.TLabelLogo.configure(font=font9)
        self.TLabelLogo.configure(relief="flat")
        self.TLabelLogo.configure(anchor='center')
        self.TLabelLogo.configure(justify='left')
        self.TLabelLogo.configure(text='''Tlabel''')
        photo_location = os.path.join(prog_location,"data/gui/browse/img/logo.jpg")
        global _img0
        _img0 = ImageTk.PhotoImage(file=photo_location)
        self.TLabelLogo.configure(image=_img0)

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _bgcolor)])
        self.TCheckbuttonKasbon = ttk.Checkbutton(self.TFrameListboxKaryawan)
        self.TCheckbuttonKasbon.place(relx=0.455, rely=0.609, relwidth=0.085
                , relheight=0.0, height=26)
        self.TCheckbuttonKasbon.configure(variable=data.gui.browse.Browse_support.TCheckboxKasbonVar)
        self.TCheckbuttonKasbon.configure(onvalue=True)
        self.TCheckbuttonKasbon.configure(offvalue=False)
        self.TCheckbuttonKasbon.configure(takefocus="")
        self.TCheckbuttonKasbon.configure(text='''Kasbon''')

    def openKasbonWindow(self):
        self.KasbonWindowapp = tk.Toplevel(root)
        self.topKasbon = KasbonWindow(self.KasbonWindowapp)

    def openKotaWindow(self):
        self.KotaWindowapp = tk.Toplevel(root)
        self.topKota = KotaWindow(self.KotaWindowapp)

    def getSelectedToListboxKaryawanTersedia(self):
        return self.ListboxKaryawanTersedia.get(tk.ANCHOR)

    def getSelectedToListboxKaryawanTerpilih(self):
        return self.ListboxKaryawanTerpilih.get(tk.ANCHOR)

    def insertToListboxKaryawanTersedia(self, idx, name):
        self.ListboxKaryawanTersedia.insert(idx, name)

    def insertToListboxKaryawanTerpilih(self, idx, name):
        self.ListboxKaryawanTerpilih.insert(idx, name)

    def deleteSelectedToListboxKaryawanTersedia(self):
        self.ListboxKaryawanTersedia.delete(tk.ANCHOR)

    def deleteSelectedToListboxKaryawanTerpilih(self):
        self.ListboxKaryawanTerpilih.delete(tk.ANCHOR)

    def getKaryawanTerpilih(self):
        return self.ListboxKaryawanTerpilih.get(0,tk.END)

    def isOnListboxKaryawanTersediaSelection(self):
        return len(self.ListboxKaryawanTersedia.curselection()) != 0
        
    def isOnListboxKaryawanTerpilihSelection(self):
        return len(self.ListboxKaryawanTerpilih.curselection()) != 0

class KasbonWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 9"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font=font9)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("248x188+400+400")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Kasbon")
        top.configure(background="#ffffff")

        self.top = top

        self.TLabelKasbon = ttk.Label(top)
        self.TLabelKasbon.place(relx=0.081, rely=0.053, height=27, width=206)
        self.TLabelKasbon.configure(background="#ffffff")
        self.TLabelKasbon.configure(foreground="#000000")
        self.TLabelKasbon.configure(font=font9)
        self.TLabelKasbon.configure(relief="flat")
        self.TLabelKasbon.configure(anchor='w')
        self.TLabelKasbon.configure(justify='left')
        self.TLabelKasbon.configure(text='''Masukkan kasbon :''')

        self.TButtonOK = ttk.Button(top)
        self.TButtonOK.place(relx=0.323, rely=0.745, height=30, width=88)
        self.TButtonOK.configure(command=data.gui.browse.Browse_support.TButtonOKCommand)
        self.TButtonOK.configure(takefocus="")
        self.TButtonOK.configure(text='''OK''')

        self.TEntryKasbon = ttk.Entry(top)
        self.TEntryKasbon.place(relx=0.081, rely=0.245, relheight=0.149
                , relwidth=0.831)
        self.TEntryKasbon.configure(textvariable=data.gui.browse.Browse_support.TEntryKasbonVar)
        self.TEntryKasbon.configure(takefocus="")
        self.TEntryKasbon.configure(cursor="ibeam")

        self.TLabelContoh = ttk.Label(top)
        self.TLabelContoh.place(relx=0.081, rely=0.415, height=51, width=202)
        self.TLabelContoh.configure(background="#ffffff")
        self.TLabelContoh.configure(foreground="#000000")
        self.TLabelContoh.configure(font=font9)
        self.TLabelContoh.configure(relief="flat")
        self.TLabelContoh.configure(anchor='w')
        self.TLabelContoh.configure(justify='left')
        self.TLabelContoh.configure(text='''( Contoh : 300000 )
Jika kosong, kasbon otomatis 0 (nol)''')

    def closeKasbonWindow(self):
        self.top.destroy()

class KotaWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 9"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font=font9)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("248x188+900+350")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Kota")
        top.configure(background="#ffffff")

        self.top = top

        self.TLabelKota = ttk.Label(top)
        self.TLabelKota.place(relx=0.081, rely=0.053, height=27, width=206)
        self.TLabelKota.configure(background="#ffffff")
        self.TLabelKota.configure(foreground="#000000")
        self.TLabelKota.configure(font=font9)
        self.TLabelKota.configure(relief="flat")
        self.TLabelKota.configure(anchor='w')
        self.TLabelKota.configure(justify='left')
        self.TLabelKota.configure(text='''Masukkan kota Anda berada sekarang :''')

        self.TButtonOKKota = ttk.Button(top)
        self.TButtonOKKota.place(relx=0.323, rely=0.745, height=30, width=88)
        self.TButtonOKKota.configure(command=data.gui.browse.Browse_support.TButtonOKKotaCommand)
        self.TButtonOKKota.configure(takefocus="")
        self.TButtonOKKota.configure(text='''OK''')

        self.TEntryKota = ttk.Entry(top)
        self.TEntryKota.place(relx=0.081, rely=0.245, relheight=0.149
                , relwidth=0.831)
        self.TEntryKota.configure(textvariable=data.gui.browse.Browse_support.TEntryKotaVar)
        self.TEntryKota.configure(takefocus="")
        self.TEntryKota.configure(cursor="ibeam")

        self.TLabelContoh = ttk.Label(top)
        self.TLabelContoh.place(relx=0.081, rely=0.415, height=51, width=202)
        self.TLabelContoh.configure(background="#ffffff")
        self.TLabelContoh.configure(foreground="#000000")
        self.TLabelContoh.configure(font=font9)
        self.TLabelContoh.configure(relief="flat")
        self.TLabelContoh.configure(anchor='w')
        self.TLabelContoh.configure(justify='left')
        self.TLabelContoh.configure(text='''Secara default, kota Bandung diset
secara otomatis''')

    def closeKotaWindow(self):
        self.top.destroy()