#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 14, 2020 11:03:09 PM +07  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #ffffff
set vTcl(pr,menuanalogcolor) #ffffff
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1366x768+267+144
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "File Configuration"
    vTcl:DefineAlias "$top" "FileWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::label $top.tLa44 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left \
        -text {Pertama, pilih file absensi terlebih dahulu dengan menekan tombol "Browse File" di bawah.} 
    vTcl:DefineAlias "$top.tLa44" "TLabelInstruksiBrowseFile" vTcl:WidgetProc "FileWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu45 \
        -takefocus {} -text {Browse File} 
    vTcl:DefineAlias "$top.tBu45" "TButtonBrowseFile" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa46 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -textvariable TLabelPathFileVar 
    vTcl:DefineAlias "$top.tLa46" "TLabelPathFile" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa47 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {( Contoh : 01CLOCK-20-02.XLS )} 
    vTcl:DefineAlias "$top.tLa47" "TLabelContohPathFile" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa48 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left \
        -text {Kedua, masukkan periode penggajian dan nominal pemasukan (kotor) pada periode tersebut.} 
    vTcl:DefineAlias "$top.tLa48" "TLabelInstruksiEntry" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {Periode           :} 
    vTcl:DefineAlias "$top.tLa49" "TLabelPeriode" vTcl:WidgetProc "FileWindow" 1
    ttk::entry $top.tEn50 \
        -font TkTextFont -textvariable TEntryPeriodeVar -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn50" "TEntryPeriode" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {Pemasukan     :} 
    vTcl:DefineAlias "$top.tLa51" "TLabelPemasukan" vTcl:WidgetProc "FileWindow" 1
    ttk::entry $top.tEn52 \
        -font TkTextFont -textvariable TEntryPemasukanVar -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn52" "TEntryPemasukan" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {( Contoh : 01-29 Februari 2020 )} 
    vTcl:DefineAlias "$top.tLa53" "TLabelContohPeriode" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {( Contoh : 5000000 )} 
    vTcl:DefineAlias "$top.tLa54" "TLabelContohPemasukan" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa55 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left \
        -text {Ketiga, pilih karyawan yang akan di-generate slip gajinya, serta masukkan kasbon masing-masing karyawan (jika ada).} 
    vTcl:DefineAlias "$top.tLa55" "TLabelInstruksiPilihKaryawan" vTcl:WidgetProc "FileWindow" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr56 \
        -borderwidth 2 -relief groove -width 766 -height 427 
    vTcl:DefineAlias "$top.tFr56" "TFrameListboxKaryawan" vTcl:WidgetProc "FileWindow" 1
    set site_3_0 $top.tFr56
    listbox $site_3_0.lis57 \
        -activestyle none -background white -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 12} \
        -foreground $vTcl(actual_gui_fg) -height 348 \
        -highlightbackground #d9d9d9 -highlightcolor black -relief groove \
        -selectbackground #c4c4c4 -selectforeground black -width 284 
    $site_3_0.lis57 configure -font "-family {Times New Roman} -size 12"
    $site_3_0.lis57 insert end text
    vTcl:DefineAlias "$site_3_0.lis57" "ListboxKaryawanTersedia" vTcl:WidgetProc "FileWindow" 1
    listbox $site_3_0.lis58 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 12} \
        -foreground $vTcl(actual_gui_fg) -height 348 \
        -highlightbackground #d9d9d9 -highlightcolor black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 284 
    $site_3_0.lis58 configure -font "-family {Times New Roman} -size 12"
    $site_3_0.lis58 insert end text
    vTcl:DefineAlias "$site_3_0.lis58" "ListboxKaryawanTerpilih" vTcl:WidgetProc "FileWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu61 \
        -command TButtonAddKaryawanCommand -takefocus {} -text >> 
    vTcl:DefineAlias "$site_3_0.tBu61" "TButtonAddKaryawan" vTcl:WidgetProc "FileWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu62 \
        -command TButtonDeleteKaryawan -takefocus {} -text << 
    vTcl:DefineAlias "$site_3_0.tBu62" "TButtonDeleteKaryawan" vTcl:WidgetProc "FileWindow" 1
    ttk::label $site_3_0.tLa63 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {~ Daftar karyawan tersedia :} 
    vTcl:DefineAlias "$site_3_0.tLa63" "TLabelListKaryawanTersedia" vTcl:WidgetProc "FileWindow" 1
    ttk::label $site_3_0.tLa64 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor w \
        -justify left -text {~ Daftar karyawan terpilih :} 
    vTcl:DefineAlias "$site_3_0.tLa64" "TLabelListKaryawanTerpilih" vTcl:WidgetProc "FileWindow" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $site_3_0.tCh45 \
        -variable tch45 -takefocus {} -text Kasbon 
    vTcl:DefineAlias "$site_3_0.tCh45" "TCheckbutton1" vTcl:WidgetProc "FileWindow" 1
    place $site_3_0.lis57 \
        -in $site_3_0 -x 0 -relx 0.039 -y 0 -rely 0.117 -width 0 \
        -relwidth 0.371 -height 0 -relheight 0.815 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis58 \
        -in $site_3_0 -x 0 -relx 0.587 -y 0 -rely 0.117 -width 0 \
        -relwidth 0.371 -height 0 -relheight 0.815 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu61 \
        -in $site_3_0 -x 0 -relx 0.509 -y 0 -rely 0.468 -width 48 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu62 \
        -in $site_3_0 -x 0 -relx 0.431 -y 0 -rely 0.468 -width 48 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa63 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.047 -width 0 \
        -relwidth 0.248 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 0 -relx 0.574 -y 0 -rely 0.047 -width 0 \
        -relwidth 0.243 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCh45 \
        -in $site_3_0 -x 0 -relx 0.444 -y 0 -rely 0.609 -width 0 \
        -relwidth 0.115 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu65 \
        -command TButtonGoCommand -takefocus {} -text Go 
    vTcl:DefineAlias "$top.tBu65" "TButtonGo" vTcl:WidgetProc "FileWindow" 1
    ttk::separator $top.tSe66 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe66" "TSeparator1" vTcl:WidgetProc "FileWindow" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu67 \
        -command TButtonCancelCommand -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu67" "TButtonCancel" vTcl:WidgetProc "FileWindow" 1
    ttk::separator $top.tSe69
    vTcl:DefineAlias "$top.tSe69" "TSeparator2" vTcl:WidgetProc "FileWindow" 1
    ttk::label $top.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 9} -relief flat -anchor center \
        -justify left -text {Logo (image)} 
    vTcl:DefineAlias "$top.tLa71" "TLabelLogo" vTcl:WidgetProc "FileWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa44 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.052 -width 0 -relwidth 0.449 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.tBu45 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.091 -width 118 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa46 \
        -in $top -x 0 -relx 0.132 -y 0 -rely 0.096 -width 0 -relwidth 0.354 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.13 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.182 -height 0 -relheight 0.031 \
        -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 0 -relx 0.044 -y 0 -rely 0.221 -width 0 -relwidth 0.077 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.tEn50 \
        -in $top -x 0 -relx 0.124 -y 0 -rely 0.221 -width 0 -relwidth 0.13 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 0 -relx 0.044 -y 0 -rely 0.26 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.tEn52 \
        -in $top -x 0 -relx 0.124 -y 0 -rely 0.26 -width 0 -relwidth 0.13 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -relx 0.264 -y 0 -rely 0.221 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.tLa54 \
        -in $top -x 0 -relx 0.264 -y 0 -rely 0.26 -width 0 -relwidth 0.194 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.326 -width 0 -relwidth 0.574 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.tFr56 \
        -in $top -x 0 -relx 0.044 -y 0 -rely 0.365 -width 0 -relwidth 0.561 \
        -height 0 -relheight 0.556 -anchor nw -bordermode ignore 
    place $top.tBu65 \
        -in $top -x 0 -relx 0.769 -y 0 -rely 0.755 -width 138 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe66 \
        -in $top -x 0 -relx 0.637 -y 0 -rely 0.039 -height 0 -relheight 0.897 \
        -anchor nw -bordermode inside 
    place $top.tBu67 \
        -in $top -x 0 -relx 0.769 -y 0 -rely 0.82 -width 138 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe69 \
        -in $top -x 0 -relx 0.673 -y 0 -rely 0.664 -width 0 -relwidth 0.293 \
        -height 0 -relheight 0.003 -anchor nw -bordermode inside 
    place $top.tLa71 \
        -in $top -x 0 -relx 0.673 -y 0 -rely 0.104 -width 0 -relwidth 0.296 \
        -height 0 -relheight 0.5 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

